# Generated by Django 4.1.2 on 2022-12-01 03:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comorbidity',
            fields=[
                ('comorbidity_id', models.AutoField(primary_key=True, serialize=False)),
                ('comorbidity_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'comorbidity',
            },
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('mg_sodium', models.FloatField()),
                ('g_protein', models.FloatField()),
                ('l_water', models.FloatField()),
                ('mg_potassium', models.FloatField()),
                ('mg_phosphorus', models.FloatField()),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='food_diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'food_diary',
            },
        ),
        migrations.CreateModel(
            name='kdiet_user',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=14)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('weight_lbs', models.FloatField()),
                ('height_inches', models.FloatField()),
            ],
            options={
                'db_table': 'kdiet_user',
            },
        ),
        migrations.CreateModel(
            name='user_comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidity_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kdietapp.comorbidity')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kdietapp.kdiet_user')),
            ],
            options={
                'db_table': 'user_comorbidity',
            },
        ),
        migrations.CreateModel(
            name='serum_levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_date', models.DateField()),
                ('potassium_level', models.FloatField()),
                ('phosphorus_level', models.FloatField()),
                ('sodium_level', models.FloatField()),
                ('creatinine_level', models.FloatField()),
                ('albumin_level', models.FloatField()),
                ('blood_sugar_level', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kdietapp.kdiet_user')),
            ],
            options={
                'db_table': 'serum_levels',
            },
        ),
        migrations.CreateModel(
            name='food_diary_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kdietapp.food_diary')),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kdietapp.food')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kdietapp.kdiet_user')),
            ],
            options={
                'db_table': 'food_diary_entry',
            },
        ),
        migrations.AddField(
            model_name='food_diary',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kdietapp.kdiet_user'),
        ),
        migrations.AddConstraint(
            model_name='user_comorbidity',
            constraint=models.UniqueConstraint(fields=('username', 'comorbidity_id'), name='user_comorbidity_CPK'),
        ),
        migrations.AddConstraint(
            model_name='serum_levels',
            constraint=models.UniqueConstraint(fields=('username', 'results_date'), name='serum_levels_CPK'),
        ),
        migrations.AddConstraint(
            model_name='food_diary_entry',
            constraint=models.UniqueConstraint(fields=('date', 'username', 'entry_id', 'meal_type'), name='food_diary_entry_CPK'),
        ),
        migrations.AddConstraint(
            model_name='food_diary',
            constraint=models.UniqueConstraint(fields=('date', 'username'), name='food_diary_CPK'),
        ),
    ]
