# Generated by Django 4.1.2 on 2022-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdietapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='entry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
